Repository OrenZhang/iWiki, pull requests merged in 2022-01, with the labels that each got.

#108 bugfix: 版本数据重复加载
  backend/modules/version/init/v1.0.10.md
  backend/modules/version/init/v1.0.9.md
  frontend/src/components/VersionLog.vue
Labels: bug

#110 bugfix: 文章统计数据有误
  backend/modules/account/views.py
  backend/modules/doc/migrations/0011_alter_doc_index_together.py
  backend/modules/doc/models.py
  backend/modules/doc/views/doc.py
  backend/modules/version/init/v1.0.10.md
Labels: bug

#112 minor: font-family
  frontend/src/assets/App.css
Labels: enhancement

#114 minor: 取消 font-family
  frontend/src/assets/App.css
Labels: enhancement

#116 minor: 合并版本日志
  backend/modules/version/init/v1.0.1.md
  backend/modules/version/init/v1.0.10.md
  backend/modules/version/init/v1.0.2.md
  backend/modules/version/init/v1.0.3.md
  backend/modules/version/init/v1.0.4.md
  backend/modules/version/init/v1.0.5.md
  backend/modules/version/init/v1.0.6.md
  backend/modules/version/init/v1.0.7.md
  backend/modules/version/init/v1.0.8.md
  backend/modules/version/init/v1.0.9.md
Labels: enhancement

#118 minor: 优化字号大小
  frontend/src/assets/App.css
Labels: enhancement

#120 feature: 代码行高亮&复制
  backend/modules/version/init/v1.0.10.md
  backend/modules/version/init/v1.0.11.md
  frontend/src/main.js
Labels: enhancement

#122 bugfix: 列表序号被遮挡
  frontend/src/assets/App.css
Labels: bug

#124 feature: 手机号登录
  backend/modules/account/backends.py
  backend/modules/account/migrations/0003_alter_user_phone.py
  backend/modules/account/models.py
  backend/modules/account/serializers.py
  backend/modules/version/init/v1.0.11.md
  backend/modules/version/init/v1.0.12.md
  frontend/src/components/LoginForm.vue
  frontend/src/locale/en.js
  frontend/src/locale/zh-hans.js
Labels: enhancement

#126 minor: 优化评论加载状态
  backend/modules/version/init/v1.0.12.md
  frontend/src/components/DocComment.vue
  frontend/src/views/Publish.vue
Labels: enhancement

#128 minor: 优化窗口弹出
  frontend/src/App.vue
Labels: enhancement

#130 feature: 全局配置
  backend/constents/__init__.py
  backend/constents/conf.py
  backend/entry/settings.py
  backend/locale/en/LC_MESSAGES/django.mo
  backend/locale/en/LC_MESSAGES/django.po
  backend/locale/zh_Hans/LC_MESSAGES/django.mo
  backend/locale/zh_Hans/LC_MESSAGES/django.po
  backend/modules/conf/__init__.py
  backend/modules/conf/admin.py
  backend/modules/conf/apps.py
  backend/modules/conf/migrations/0001_initial.py
  backend/modules/conf/migrations/__init__.py
  backend/modules/conf/models.py
  backend/modules/sms/views.py
  backend/modules/version/init/v1.0.12.md
Labels: enhancement

#132 minor: 优化窗口弹出
  frontend/src/App.vue
  frontend/src/components/DocComment.vue
  frontend/src/components/RepoManage.vue
Labels: enhancement

#134 minor: 优化颜色引用
  frontend/public/extra-assests/imgs/bg-4.jpg
  frontend/src/assets/Admin.css
  frontend/src/assets/App.css
  frontend/src/assets/Doc.css
  frontend/src/assets/Home.css
  frontend/src/assets/Login.css
  frontend/src/assets/Publish.css
  frontend/src/assets/RegisterForm.css
  frontend/src/assets/RepoDetail.css
  frontend/src/assets/UserInfoBox.css
  frontend/src/assets/UserSelf.css
  frontend/src/components/ActiveUsers.vue
  frontend/src/components/AdminDoc.vue
  frontend/src/components/AdminMember.vue
  frontend/src/components/DocCatalogue.vue
  frontend/src/components/DocComment.vue
  frontend/src/components/HUserInfoBox.vue
  frontend/src/components/RegisterForm.vue
  frontend/src/components/RepoCards.vue
  frontend/src/components/RepoDetailInfo.vue
  frontend/src/components/VersionLog.vue
  frontend/src/views/Admin.vue
  frontend/src/views/Login.vue
  frontend/src/views/Publish.vue
  frontend/src/views/Repo.vue
  frontend/src/views/User.vue
  frontend/src/views/UserSelf.vue
Labels: enhancement

#136 bugfix: 图表渲染
  backend/modules/version/init/v1.0.12.md
  backend/modules/version/init/v1.0.13.md
  frontend/src/components/DocPublishChart.vue
Labels: bug

#138 bugfix: 小屏设备边距
  frontend/src/assets/App.css
  frontend/src/assets/Doc.css
Labels: bug

#142 build: 更新依赖
  frontend/package.json
  frontend/public/extra-assests/mermaid.min.js
  frontend/yarn.lock
Labels: dependencies

#144 bugfix: 样式异常
  frontend/package.json
  frontend/yarn.lock
Labels: bug

#146 feature: 首页通知
  backend/entry/urls.py
  backend/locale/en/LC_MESSAGES/django.mo
  backend/locale/en/LC_MESSAGES/django.po
  backend/locale/zh_Hans/LC_MESSAGES/django.mo
  backend/locale/zh_Hans/LC_MESSAGES/django.po
  backend/modules/conf/migrations/0002_conf_sensitive.py
  backend/modules/conf/models.py
  backend/modules/conf/urls.py
  backend/modules/conf/views.py
  backend/modules/version/init/v1.0.13.md
  backend/modules/version/init/v1.0.14.md
  frontend/src/assets/Home.css
  frontend/src/views/Home.vue
Labels: enhancement

#148 minor: 优化样式
  frontend/src/assets/Home.css
Labels: enhancement

#150 minor: 优化样式
  frontend/src/assets/Home.css
  frontend/src/views/Home.vue
Labels: enhancement

#152 bugfix: dialog esc
  frontend/src/components/DocComment.vue
Labels: bug

#154 minor: 优化文件上传文件名
  backend/entry/settings.py
  backend/modules/cos/client.py
  backend/modules/cos/views.py
  frontend/src/components/HUserInfoBox.vue
  frontend/src/locale/en.js
  frontend/src/locale/zh-hans.js
Labels: enhancement

#156 bugfix: 鉴权错误
  backend/modules/doc/permissions.py
  backend/modules/repo/permissions.py
  backend/modules/repo/views.py
Labels: bug

#160 bugfix: 申请错误
  backend/modules/repo/permissions.py
  backend/modules/repo/views.py
Labels: bug

#162 bugfix: 库成员处理人显示异常
  backend/modules/repo/admin.py
Labels: bug

#164 minor: 移除配置/国际化接口的登录校验
  backend/modules/conf/views.py
  backend/modules/i18n/views.py
Labels: enhancement

#166 bugfix: 协作接口鉴权错误
  backend/modules/doc/permissions.py
Labels: bug

#168 bugfix: chart resize
  frontend/src/components/DocPublishChart.vue
Labels: bug

#170 minor: 拆分API请求
  frontend/src/App.vue
  frontend/src/api/modules/comment.js
  frontend/src/api/modules/common.js
  frontend/src/api/modules/doc.js
  frontend/src/api/modules/repo.js
  frontend/src/api/modules/user.js
  frontend/src/components/ActiveUsers.vue
  frontend/src/components/AdminDoc.vue
  frontend/src/components/AdminMember.vue
  frontend/src/components/DocComment.vue
  frontend/src/components/DocInfoBox.vue
  frontend/src/components/DocManage.vue
  frontend/src/components/DocPublishChart.vue
  frontend/src/components/EditUserInfo.vue
  frontend/src/components/ErrorPage.vue
  frontend/src/components/HUserInfoBox.vue
  frontend/src/components/LoginForm.vue
  frontend/src/components/PinDocList.vue
  frontend/src/components/RegisterForm.vue
  frontend/src/components/RepoCards.vue
  frontend/src/components/RepoDetailInfo.vue
  frontend/src/components/RepoDocList.vue
  frontend/src/components/RepoManage.vue
  frontend/src/components/VersionLog.vue
  frontend/src/main.js
  frontend/src/store/index.js
  frontend/src/views/Admin.vue
  frontend/src/views/Doc.vue
  frontend/src/views/DocMobile.vue
  frontend/src/views/Home.vue
  frontend/src/views/Publish.vue
  frontend/src/views/Repo.vue
  frontend/src/views/RepoDetail.vue
  frontend/src/views/User.vue
  frontend/src/views/UserSelf.vue
Labels: enhancement

#172 bugfix: 参数位置错误
  frontend/src/api/modules/doc.js
Labels: bug

#174 bugfix: 头图不占满
  frontend/src/views/Repo.vue
Labels: bug

#176 bugfix: 图表空白
  frontend/src/components/DocPublishChart.vue
Labels: bug

#180 minor: 更新依赖
  frontend/package.json
  frontend/yarn.lock
Labels: enhancement

#184 bugfix: 没有通知时通知栏不消失
  frontend/src/views/Home.vue
Labels: bug

#186 bugfix: 用户名重复异常
  backend/modules/account/serializers.py
  backend/modules/account/views.py
Labels: bug

#188 minor: 更新依赖&优化样式
  frontend/package.json
  frontend/src/assets/Admin.css
  frontend/src/assets/Home.css
  frontend/src/assets/Publish.css
  frontend/src/views/Home.vue
  frontend/src/views/Repo.vue
  frontend/yarn.lock
Labels: dependencies

#190 bugfix: 切换组页码异常
  frontend/src/components/AdminDoc.vue
  frontend/src/components/AdminMember.vue
Labels: bug

#196 feature: 日志模块
  backend/entry/settings.py
  backend/locale/en/LC_MESSAGES/django.mo
  backend/locale/en/LC_MESSAGES/django.po
  backend/locale/zh_Hans/LC_MESSAGES/django.mo
  backend/locale/zh_Hans/LC_MESSAGES/django.po
  backend/modules/account/views.py
  backend/modules/log/__init__.py
  backend/modules/log/admin.py
  backend/modules/log/apps.py
  backend/modules/log/migrations/0001_initial.py
  backend/modules/log/migrations/__init__.py
  backend/modules/log/models.py
  backend/modules/log/utils.py
Labels: feature

#198 feature: 页面标题展示
  .gitignore
  backend/modules/version/init/v1.0.15.md
  backend/modules/version/init/v1.0.16.md
  frontend/package.json
  frontend/src/locale/en.js
  frontend/src/locale/zh-hans.js
  frontend/src/main.js
  frontend/src/utils/controller.js
  frontend/src/views/Admin.vue
  frontend/src/views/Doc.vue
  frontend/src/views/DocMobile.vue
  frontend/src/views/Home.vue
  frontend/src/views/Publish.vue
  frontend/src/views/Repo.vue
  frontend/src/views/RepoDetail.vue
  frontend/src/views/User.vue
  frontend/src/views/UserSelf.vue
  frontend/yarn.lock
Labels: feature

#200 minor: 字段优化
  backend/modules/log/migrations/0002_alter_log_operator.py
Labels: enhancement

#202 bugfix: 评论版本不生效
  backend/modules/doc/views/comment.py
Labels: bug

#204 feature: 热门文章
  backend/modules/doc/migrations/0012_doc_pv_docversion_pv.py
  backend/modules/doc/models.py
  backend/modules/doc/views/doc.py
  backend/modules/version/init/v1.0.16.md
  frontend/src/components/DocInfoBox.vue
  frontend/src/components/RepoDocList.vue
  frontend/src/locale/en.js
  frontend/src/locale/zh-hans.js
Labels: feature

#206 bugfix: 搜索页码不重置
  frontend/src/views/Home.vue
Labels: bug

#208 bugfix: 更新 PV 导致文章更新时间异常
  backend/modules/doc/views/doc.py
Labels: bug

#210 minor: 修改 API 默认目录响应
  backend/entry/settings.py
  backend/entry/settings_tpl.json
  backend/entry/urls.py
  backend/modules/home/__init__.py
  backend/modules/home/apps.py
  backend/modules/home/migrations/__init__.py
  backend/modules/home/urls.py
  backend/modules/home/views.py
  backend/utils/exceptions.py
Labels: enhancement

#214 minor: 优化代码高亮
  frontend/src/main.js
Labels: enhancement

#218 minor: 增加首页图表展示配置
  backend/constents/conf.py
  frontend/src/views/Home.vue
Labels: enhancement

#221 bugfix: 翻译错误
  backend/entry/settings.py
  backend/locale/en/LC_MESSAGES/django.mo
  backend/locale/en/LC_MESSAGES/django.po
  backend/locale/zh_Hans/LC_MESSAGES/django.mo
  backend/locale/zh_Hans/LC_MESSAGES/django.po
Labels: bug

#222 feature: 网站持续运行时间
  backend/constents/conf.py
  frontend/src/App.vue
  frontend/src/components/AppFooter.vue
  frontend/src/locale/en.js
  frontend/src/locale/zh-hans.js
  frontend/src/store/index.js
  frontend/src/views/Home.vue
Labels: feature

#224 minor: 更新日志
  README.md
  assets/favicon.png
  assets/wiki.incv.net_(Laptop).webp
  backend/constents/conf.py
  backend/modules/version/init/v1.1.0.md
Labels: documentation

#226 bugfix: 网站运行时间初始化错误
  frontend/src/components/AppFooter.vue
Labels: bug

#228 minor: 更新README
  README.md
Labels: documentation

#230 minor: 更新 README
  README.md
Labels: documentation

#232 minor: 细节优化
  README.md
  backend/constents/conf.py
  backend/entry/settings.py
  backend/entry/settings_tpl.json
  frontend/src/views/Publish.vue
Labels: enhancement

#234 feature: 容器化部署
  .gitignore
  README.md
  backend/.env_tpl
  backend/Dockerfile
  backend/bin/run.sh
  backend/entry/settings.py
  backend/entry/settings_tpl.json
  backend/modules/version/init/v1.2.0.md
  backend/requirements.txt
  backend/uwsgi.ini
Labels: feature

#236 bugfix: 权限异常
  backend/Dockerfile
Labels: bug

#238 bugfix: 权限异常
  backend/bin/run.sh
  backend/modules/version/init/v1.2.1.md
Labels: bug

#240 bugfix: 自动构建异常
  backend/Dockerfile
Labels: bug

#242 minor: 更新 README
  README.md
Labels: documentation

#244 minor: 优化国际化显示
  frontend/src/App.vue
Labels: enhancement

#248 feature: 动态链接配置
  backend/constents/conf.py
  frontend/src/App.vue
  frontend/src/assets/App.css
  frontend/src/store/index.js
Labels: feature

#250 minor: 更新日志
  backend/modules/version/init/v1.2.1.md
  backend/modules/version/init/v1.2.2.md
Labels: documentation
